import { createClient } from "npm:@supabase/supabase-js@2.110.9";
import { bankAmountToCents,bankResponseData,normalizeBankStatus,PAID_BANK_STATUSES } from "../_shared/pix.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"",SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",BANCO_INTER_API_KEY=Deno.env.get("BANCO_INTER_API_KEY")??"";
const BRIDGE_BASE_URL=(Deno.env.get("BANCO_INTER_BRIDGE_BASE_URL")??"https://inter.btsolucao.com.br").replace(/\/$/,"");
const admin=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
function corsHeaders(request:Request){const origin=request.headers.get("origin")??"";const allowed=new Set(["https://monitoria.cam","https://www.monitoria.cam","https://vip.monitoria.cam","http://localhost:3000",Deno.env.get("APP_URL")?.replace(/\/$/,"")??""]);return {"Access-Control-Allow-Origin":allowed.has(origin)?origin:"https://monitoria.cam","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS",Vary:"Origin"}}
function json(request:Request,body:Record<string,unknown>,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders(request),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function objectValue(v:unknown){return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{} }
function uuid(v:unknown){const s=String(v??"").trim();return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s)?s:null}
async function currentUser(request:Request){const t=request.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1]?.trim();if(!t)return null;const {data,error}=await admin.auth.getUser(t);return error?null:data.user}
async function canManage(org:string,userId:string){const {data,error}=await admin.from("organization_members").select("role").eq("organization_id",org).eq("user_id",userId).maybeSingle();return !error&&["owner","admin"].includes(String(data?.role))}
async function activateVip(invoiceId:string,userId:string){const {data:contract}=await admin.from("vip_contracts").select("id,status").eq("invoice_id",invoiceId).neq("status","cancelled").order("created_at",{ascending:false}).limit(1).maybeSingle();if(!contract)return {vip:false,active:false,pending:false};if(contract.status==="active")return {vip:true,active:true,pending:false,contractId:String(contract.id),duplicate:true};if(contract.status!=="paid_pending_activation")return {vip:true,active:false,pending:true,contractId:String(contract.id)};const {data,error}=await admin.rpc("activate_paid_vip_contract_v1",{p_contract_id:String(contract.id),p_actor_user_id:userId});if(error){console.error("activate_paid_vip_contract_v1:",error.message);return {vip:true,active:false,pending:true,contractId:String(contract.id),error:"vip_activation_pending"}}const result=objectValue(data),active=result.success===true&&String(result.status??"")==="active";return {vip:true,active,pending:!active,contractId:String(contract.id),result}}

Deno.serve(async(request:Request)=>{
  if(request.method==="OPTIONS")return new Response("ok",{headers:corsHeaders(request)});if(request.method!=="POST")return json(request,{success:false,error:"method_not_allowed"},405);
  try{
    if(!BANCO_INTER_API_KEY)return json(request,{success:false,error:"banco_inter_not_configured"},503);
    const user=await currentUser(request);if(!user)return json(request,{success:false,error:"unauthorized"},401);
    const body=await request.json().catch(()=>({})),paymentId=uuid((body as Record<string,unknown>).payment_id);if(!paymentId)return json(request,{success:false,error:"invalid_payment_id"},400);
    const {data:payment}=await admin.from("billing_pix_payments").select("id,organization_id,invoice_id,status,txid,expires_at,confirmed_at,error_code,error_message").eq("id",paymentId).maybeSingle();if(!payment)return json(request,{success:false,error:"payment_not_found"},404);if(!(await canManage(String(payment.organization_id),user.id)))return json(request,{success:false,error:"not_authorized"},403);
    const {data:invoice}=await admin.from("billing_invoices").select("id,invoice_number,status,service_period_start,service_period_end,paid_at").eq("id",payment.invoice_id).maybeSingle();
    if(payment.status==="confirmed"||invoice?.status==="paid"){const vip=await activateVip(String(payment.invoice_id),user.id);return json(request,{success:true,status:"paid",payment_id:payment.id,invoice_id:payment.invoice_id,invoice_number:invoice?.invoice_number??null,paid_at:payment.confirmed_at??invoice?.paid_at??null,period_start:invoice?.service_period_start??null,period_end:invoice?.service_period_end??null,vip_activation:vip,activation_pending:vip.vip===true&&vip.active!==true,message:vip.vip?(vip.active?"Pagamento confirmado e ambiente VIP ativado.":"Pagamento confirmado. A ativação VIP será tentada novamente automaticamente."):"Pagamento já confirmado."})}
    if(["expired","cancelled","failed"].includes(String(payment.status)))return json(request,{success:false,status:payment.status,payment_id:payment.id,error:payment.error_code??`payment_${payment.status}`,message:payment.error_message??"Esta cobrança não está mais disponível."});
    if(payment.expires_at&&new Date(String(payment.expires_at)).getTime()<=Date.now()){await admin.rpc("expire_monitoria_pix_payments");return json(request,{success:false,status:"expired",payment_id:payment.id,message:"O Pix expirou. Gere uma nova cobrança."})}
    if(!payment.txid)return json(request,{success:false,status:"pending",payment_id:payment.id,message:"A cobrança ainda está sendo preparada."});
    const response=await fetch(`${BRIDGE_BASE_URL}/get.php?txid=${encodeURIComponent(payment.txid)}`,{headers:{Authorization:`Bearer ${BANCO_INTER_API_KEY}`,"Content-Type":"application/json"},signal:AbortSignal.timeout(20000)});const raw=await response.text();let provider:Record<string,unknown>={};try{provider=objectValue(JSON.parse(raw))}catch{provider={raw:raw.slice(0,2000),httpStatus:response.status}}if(!response.ok){await admin.rpc("mark_monitoria_pix_checked",{p_payment_id:payment.id,p_bank_status:`HTTP_${response.status}`,p_provider_payload:provider});return json(request,{success:false,status:"pending",payment_id:payment.id,message:"O banco ainda não pôde confirmar o pagamento."})}
    const data=bankResponseData(provider),bankStatus=normalizeBankStatus(data.status??data.situacao??data.state);if(!PAID_BANK_STATUSES.has(bankStatus)){await admin.rpc("mark_monitoria_pix_checked",{p_payment_id:payment.id,p_bank_status:bankStatus||"PENDENTE",p_provider_payload:provider});return json(request,{success:false,status:"pending",bank_status:bankStatus||"PENDENTE",payment_id:payment.id,message:"Pagamento ainda não confirmado."})}
    const {data:confirmation,error}=await admin.rpc("apply_confirmed_monitoria_payment",{p_payment_id:payment.id,p_txid:payment.txid,p_paid_amount_cents:bankAmountToCents(data),p_provider_status:bankStatus,p_provider_payload:provider,p_confirmed_at:new Date().toISOString()});if(error)return json(request,{success:false,error:"payment_confirmation_failed"},500);const result=objectValue(confirmation);if(result.success!==true)return json(request,{success:false,status:String(result.status??"manual_review"),payment_id:payment.id,reason:result.reason??"manual_review",message:result.reason==="amount_mismatch"?"O valor recebido é diferente da fatura e precisa de revisão.":"O pagamento precisa de revisão antes da ativação."});
    const vip=await activateVip(String(payment.invoice_id),user.id);return json(request,{success:true,status:"paid",payment_id:payment.id,invoice_id:payment.invoice_id,invoice_number:result.invoiceNumber??invoice?.invoice_number,period_start:result.periodStart??null,period_end:result.periodEnd??null,activated_cameras:Array.isArray(result.activatedCameras)?result.activatedCameras:[],assistant_packs:Array.isArray(result.assistantPacks)?result.assistantPacks:[],assistant_interactions:result.assistantInteractions??null,balance:result.balance??null,duplicate:result.duplicate===true,vip_activation:vip,activation_pending:vip.vip===true&&vip.active!==true,message:vip.vip?(vip.active?"Pagamento confirmado e ambiente VIP ativado.":"Pagamento confirmado. A ativação VIP será tentada novamente automaticamente."):"Pagamento confirmado e serviços ativados."});
  }catch(error){console.error("monitoria-check-pix:",error instanceof Error?error.message:String(error));return json(request,{success:false,status:"error",error:"unexpected_error",message:"Não foi possível consultar o pagamento."},500)}
});
