import { createClient } from "npm:@supabase/supabase-js@2.110.9";
import { bankAmountToCents,bankResponseData,normalizeBankStatus,PAID_BANK_STATUSES } from "../_shared/pix.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"",SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",BANCO_INTER_API_KEY=Deno.env.get("BANCO_INTER_API_KEY")??"";
const BRIDGE_BASE_URL=(Deno.env.get("BANCO_INTER_BRIDGE_BASE_URL")??"https://inter.btsolucao.com.br").replace(/\/$/,"");
const admin=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
function json(body:Record<string,unknown>,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function objectValue(v:unknown){return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{} }
function decode(token:string){const parts=token.split(".");if(parts.length!==3)return null;try{const n=parts[1].replace(/-/g,"+").replace(/_/g,"/");return objectValue(JSON.parse(atob(n.padEnd(Math.ceil(n.length/4)*4,"="))))}catch{return null}}
function serviceAuthorized(request:Request){const [scheme,token]=((request.headers.get("authorization")??"").split(/\s+/,2));if(scheme?.toLowerCase()!=="bearer"||!token)return false;if(SERVICE_ROLE_KEY&&token===SERVICE_ROLE_KEY)return true;const payload=decode(token);if(String(payload?.role??"")!=="service_role")return false;const exp=Number(payload?.exp??0);return !Number.isFinite(exp)||exp<=0||exp>Math.floor(Date.now()/1000)}
async function activateVip(contractId:string){const {data,error}=await admin.rpc("activate_paid_vip_contract_v1",{p_contract_id:contractId,p_actor_user_id:null});if(error){console.error(`Falha ao ativar contrato VIP ${contractId}:`,error.message);return {contractId,result:"activation_pending",error:error.message}}const r=objectValue(data);return {contractId,result:r.success===true?"active":"activation_pending",duplicate:r.duplicate===true,projectId:r.projectId??null,activeCameras:r.activeCameras??null,remainingCapacity:r.remainingCapacity??null}}
async function checkPayment(payment:{id:string;txid:string;amount_cents:number}){
  try{
    const response=await fetch(`${BRIDGE_BASE_URL}/get.php?txid=${encodeURIComponent(payment.txid)}`,{headers:{Authorization:`Bearer ${BANCO_INTER_API_KEY}`,"Content-Type":"application/json"},signal:AbortSignal.timeout(18000)});const raw=await response.text();let provider:Record<string,unknown>={};try{provider=objectValue(JSON.parse(raw))}catch{provider={raw:raw.slice(0,2000),httpStatus:response.status}}if(!response.ok){await admin.rpc("mark_monitoria_pix_checked",{p_payment_id:payment.id,p_bank_status:`HTTP_${response.status}`,p_provider_payload:provider});return {paymentId:payment.id,result:"provider_error"}}
    const data=bankResponseData(provider),bankStatus=normalizeBankStatus(data.status??data.situacao??data.state);if(!PAID_BANK_STATUSES.has(bankStatus)){await admin.rpc("mark_monitoria_pix_checked",{p_payment_id:payment.id,p_bank_status:bankStatus||"PENDENTE",p_provider_payload:provider});return {paymentId:payment.id,result:"pending",bankStatus}}
    const {data:confirmation,error}=await admin.rpc("apply_confirmed_monitoria_payment",{p_payment_id:payment.id,p_txid:payment.txid,p_paid_amount_cents:bankAmountToCents(data),p_provider_status:bankStatus,p_provider_payload:provider,p_confirmed_at:new Date().toISOString()});if(error)return {paymentId:payment.id,result:"confirmation_error"};const result=objectValue(confirmation);let vipActivation:Record<string,unknown>|null=null;if(result.success===true&&result.vipContractId)vipActivation=await activateVip(String(result.vipContractId));return {paymentId:payment.id,result:result.success===true?"confirmed":"manual_review",duplicate:result.duplicate===true,assistantPacks:result.assistantPacks??[],vipActivation};
  }catch(error){console.error(`Falha ao consultar ${payment.id}:`,error instanceof Error?error.message:String(error));return {paymentId:payment.id,result:"unexpected_error"}}
}

Deno.serve(async(request:Request)=>{
  if(request.method!=="POST")return json({success:false,error:"method_not_allowed"},405);if(!serviceAuthorized(request))return json({success:false,error:"unauthorized"},401);if(!BANCO_INTER_API_KEY)return json({success:false,error:"banco_inter_not_configured"},503);
  try{
    const {data:deadlines,error:deadlinesError}=await admin.rpc("process_monitoria_billing_deadlines");if(deadlinesError)return json({success:false,error:"billing_deadlines_failed"},500);
    const {data:payments,error:paymentsError}=await admin.from("billing_pix_payments").select("id,txid,amount_cents").in("status",["pending","manual_review"]).not("txid","is",null).gt("expires_at",new Date().toISOString()).order("last_checked_at",{ascending:true,nullsFirst:true}).limit(25);if(paymentsError)return json({success:false,error:"pending_payments_unavailable"},500);
    const results:Array<Record<string,unknown>>=[];for(const p of payments??[])results.push(await checkPayment({id:String(p.id),txid:String(p.txid),amount_cents:Number(p.amount_cents)}));
    const {data:pending,error:pendingError}=await admin.from("vip_contracts").select("id").eq("status","paid_pending_activation").order("paid_at",{ascending:true,nullsFirst:true}).limit(25);const vipActivations:Array<Record<string,unknown>>=[];if(pendingError)console.error("pending vip activations:",pendingError.message);else for(const c of pending??[])vipActivations.push(await activateVip(String(c.id)));
    return json({success:true,deadlines:objectValue(deadlines),scannedPayments:results.length,confirmedPayments:results.filter(i=>i.result==="confirmed").length,manualReview:results.filter(i=>i.result==="manual_review").length,results,vipActivations,activatedVipContracts:vipActivations.filter(i=>i.result==="active").length,processedAt:new Date().toISOString()});
  }catch(error){console.error("monitoria-process-billing:",error instanceof Error?error.message:String(error));return json({success:false,error:"unexpected_error"},500)}
});
