alter table public.camera_usage_monthly
  add column if not exists plan_code text null,
  add column if not exists jobs_count bigint not null default 0,
  add column if not exists completed_jobs bigint not null default 0,
  add column if not exists failed_jobs bigint not null default 0,
  add column if not exists relevant_events bigint not null default 0,
  add column if not exists review_required_events bigint not null default 0,
  add column if not exists total_model_calls bigint not null default 0,
  add column if not exists primary_calls bigint not null default 0,
  add column if not exists verifier_calls bigint not null default 0,
  add column if not exists experimental_calls bigint not null default 0,
  add column if not exists production_ai_cost_usd numeric(20,10) not null default 0,
  add column if not exists experimental_ai_cost_usd numeric(20,10) not null default 0,
  add column if not exists avg_latency_ms numeric(14,2) null,
  add column if not exists p95_latency_ms numeric(14,2) null,
  add column if not exists avg_confidence numeric(8,6) null,
  add column if not exists review_rate_basis_points integer not null default 0,
  add column if not exists escalation_rate_basis_points integer not null default 0,
  add column if not exists observed_from timestamptz null,
  add column if not exists observed_to timestamptz null,
  add column if not exists observation_hours numeric(14,4) not null default 0,
  add column if not exists known_ai_cost_brl_cents integer not null default 0,
  add column if not exists projected_30d_ai_cost_usd numeric(20,10) null,
  add column if not exists projected_30d_ai_cost_brl_cents integer null,
  add column if not exists routing_telemetry_available boolean not null default false;
create index if not exists camera_usage_monthly_org_month_ai_idx
  on public.camera_usage_monthly(organization_id, usage_month desc);
