-- MonitorIA — correção de encerramento da Fase 9
-- Garante triagem econômica, limite mensal de verificações e telemetria fiel.

begin;

alter table public.analysis_routing_decisions
  add column if not exists verification_limited_by_plan boolean not null default false;

comment on column public.analysis_routing_decisions.verification_limited_by_plan is
  'A verificação foi solicitada pelo score, mas bloqueada pelo limite mensal do plano ou por repetir o mesmo modelo forte.';

create table if not exists public.analysis_verification_reservations (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  camera_id uuid not null references public.cameras(id) on delete cascade,
  analysis_job_id uuid not null references public.analysis_jobs(id) on delete cascade,
  usage_month date not null,
  plan_code text not null,
  allowed boolean not null,
  limit_percent smallint not null,
  jobs_observed integer not null,
  verifications_observed integer not null,
  ai_budget_to_date_cents integer not null,
  ai_cost_observed_cents integer not null,
  verification_reserve_cents integer not null,
  created_at timestamptz not null default now(),
  constraint analysis_verification_reservations_job_uidx unique (analysis_job_id),
  constraint analysis_verification_reservations_month_check
    check (usage_month = date_trunc('month', usage_month)::date),
  constraint analysis_verification_reservations_limit_check
    check (limit_percent between 0 and 100),
  constraint analysis_verification_reservations_counts_check
    check (
      jobs_observed >= 0
      and verifications_observed >= 0
      and ai_budget_to_date_cents >= 0
      and ai_cost_observed_cents >= 0
      and verification_reserve_cents >= 0
    )
);

create index if not exists analysis_verification_reservations_camera_month_idx
  on public.analysis_verification_reservations (
    camera_id,
    usage_month,
    allowed
  );

alter table public.analysis_verification_reservations enable row level security;

revoke all on public.analysis_verification_reservations
  from public, anon, authenticated;
grant all on public.analysis_verification_reservations to service_role;

comment on table public.analysis_verification_reservations is
  'Reservas atômicas que impedem verificações acima do percentual mensal definido no catálogo comercial.';

create or replace function public.reserve_monitoria_analysis_verification(
  p_organization_id uuid,
  p_camera_id uuid,
  p_analysis_job_id uuid,
  p_plan_code text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_month date := date_trunc('month', current_date)::date;
  v_limit smallint := 0;
  v_jobs integer := 0;
  v_used integer := 0;
  v_target_cogs_cents integer := 0;
  v_warning_percent integer := 80;
  v_usd_to_brl numeric := 5;
  v_monthly_ai_budget_cents integer := 0;
  v_budget_to_date_cents integer := 0;
  v_cost_observed_cents integer := 0;
  v_pending_reserve_cents integer := 0;
  v_verification_reserve_cents integer := 5;
  v_days_in_month integer := 1;
  v_elapsed_days integer := 1;
  v_rate_allowed boolean := false;
  v_budget_allowed boolean := false;
  v_allowed boolean := false;
  v_existing boolean;
begin
  perform private.require_monitoria_service_role();

  select reservation.allowed
    into v_existing
  from public.analysis_verification_reservations reservation
  where reservation.analysis_job_id = p_analysis_job_id;

  if found then
    return v_existing;
  end if;

  if not exists (
    select 1
    from public.analysis_jobs job
    where job.id = p_analysis_job_id
      and job.organization_id = p_organization_id
      and job.camera_id = p_camera_id
  ) then
    raise exception 'analysis_job_scope_mismatch';
  end if;

  select coalesce(plan.maximum_escalation_percent, 0)
    into v_limit
  from public.camera_plan_catalog plan
  where plan.code = p_plan_code
    and plan.is_active = true;

  v_limit := coalesce(v_limit, 0);

  select coalesce(target.target_max_cogs_cents, 0),
         settings.warning_target_percent,
         settings.usd_to_brl
    into v_target_cogs_cents,
         v_warning_percent,
         v_usd_to_brl
  from public.ai_cost_settings settings
  left join lateral (
    select margin.target_max_cogs_cents
    from public.plan_margin_target_versions margin
    where margin.plan_code = p_plan_code
      and margin.valid_from <= now()
      and (margin.valid_to is null or margin.valid_to > now())
    order by margin.valid_from desc
    limit 1
  ) target on true;

  v_monthly_ai_budget_cents := greatest(
    0,
    floor(
      v_target_cogs_cents::numeric
      * greatest(0, least(v_warning_percent, 100))
      / 100
    )::integer
  );
  v_days_in_month := extract(
    day from (v_month + interval '1 month - 1 day')
  )::integer;
  v_elapsed_days := extract(day from current_date)::integer;
  v_budget_to_date_cents := floor(
    v_monthly_ai_budget_cents::numeric
    * v_elapsed_days
    / greatest(v_days_in_month, 1)
  )::integer;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_camera_id::text || ':verification:' || v_month::text,
      0
    )
  );

  -- Repete a leitura sob o lock para manter idempotência com requisições
  -- concorrentes do mesmo job.
  select reservation.allowed
    into v_existing
  from public.analysis_verification_reservations reservation
  where reservation.analysis_job_id = p_analysis_job_id;

  if found then
    return v_existing;
  end if;

  select count(*)::integer
    into v_jobs
  from public.analysis_jobs job
  where job.organization_id = p_organization_id
    and job.camera_id = p_camera_id
    and job.started_at >= v_month
    and job.started_at < v_month + interval '1 month';

  select count(*)::integer
    into v_used
  from (
    select job.id as analysis_job_id
    from public.analysis_jobs job
    where job.organization_id = p_organization_id
      and job.camera_id = p_camera_id
      and job.started_at >= v_month
      and job.started_at < v_month + interval '1 month'
      and jsonb_path_exists(
        coalesce(job.model_chain, '[]'::jsonb),
        '$[*] ? (@.role == "verifier" || @.role == "escalation")'
      )

    union

    select reservation.analysis_job_id
    from public.analysis_verification_reservations reservation
    where reservation.organization_id = p_organization_id
      and reservation.camera_id = p_camera_id
      and reservation.usage_month = v_month
      and reservation.allowed = true
  ) used;

  select round(
           coalesce(sum(usage.estimated_cost_usd), 0)
           * v_usd_to_brl
           * 100
         )::integer
    into v_cost_observed_cents
  from public.usage_events usage
  where usage.organization_id = p_organization_id
    and usage.camera_id = p_camera_id
    and usage.created_at >= v_month
    and usage.created_at < v_month + interval '1 month'
    and coalesce(usage.metadata->>'role', '') <> 'ab_candidate';

  select greatest(
           1,
           coalesce(
             ceil(
               avg(usage.estimated_cost_usd)
               * v_usd_to_brl
               * 100
               * 1.25
             )::integer,
             5
           )
         )
    into v_verification_reserve_cents
  from public.usage_events usage
  where usage.organization_id = p_organization_id
    and usage.camera_id = p_camera_id
    and usage.created_at >= now() - interval '30 days'
    and usage.metadata->>'role' in ('verifier', 'escalation');

  select coalesce(sum(reservation.verification_reserve_cents), 0)::integer
    into v_pending_reserve_cents
  from public.analysis_verification_reservations reservation
  where reservation.organization_id = p_organization_id
    and reservation.camera_id = p_camera_id
    and reservation.usage_month = v_month
    and reservation.allowed = true
    and not exists (
      select 1
      from public.usage_events usage
      where usage.analysis_job_id = reservation.analysis_job_id
        and usage.metadata->>'role' in ('verifier', 'escalation')
    );

  v_rate_allowed :=
    v_limit > 0
    and v_jobs > 0
    and (v_used + 1) * 100 <= v_jobs * v_limit;

  v_budget_allowed :=
    v_monthly_ai_budget_cents > 0
    and v_cost_observed_cents
      + v_pending_reserve_cents
      + v_verification_reserve_cents
      <= v_budget_to_date_cents;

  v_allowed := v_rate_allowed and v_budget_allowed;

  insert into public.analysis_verification_reservations (
    organization_id,
    camera_id,
    analysis_job_id,
    usage_month,
    plan_code,
    allowed,
    limit_percent,
    jobs_observed,
    verifications_observed,
    ai_budget_to_date_cents,
    ai_cost_observed_cents,
    verification_reserve_cents
  )
  values (
    p_organization_id,
    p_camera_id,
    p_analysis_job_id,
    v_month,
    p_plan_code,
    v_allowed,
    v_limit,
    v_jobs,
    v_used,
    v_budget_to_date_cents,
    v_cost_observed_cents,
    v_verification_reserve_cents
  )
  on conflict (analysis_job_id) do nothing;

  return v_allowed;
end;
$function$;

revoke all on function public.reserve_monitoria_analysis_verification(uuid, uuid, uuid, text)
  from public, anon, authenticated;
grant execute on function public.reserve_monitoria_analysis_verification(uuid, uuid, uuid, text)
  to service_role;

-- A gravação anterior chamava de "final" tanto a primária quanto a verificadora.
-- O último item de model_chain contém o papel real e permite corrigir o histórico.
update public.usage_events usage
set metadata = jsonb_set(
  usage.metadata,
  '{role}',
  to_jsonb(
    coalesce(
      (
        select chain.item->>'role'
        from jsonb_array_elements(usage.metadata->'model_chain')
          with ordinality as chain(item, position)
        order by chain.position desc
        limit 1
      ),
      'final'
    )
  ),
  true
)
where usage.metadata->>'purpose' = 'continuous_event'
  and usage.metadata->>'role' = 'final'
  and jsonb_typeof(usage.metadata->'model_chain') = 'array'
  and jsonb_array_length(usage.metadata->'model_chain') > 0;

create or replace function private.sync_monitoria_daily_escalation_metrics()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  new.escalation_calls := greatest(
    coalesce(new.escalation_calls, 0),
    coalesce(new.verifier_calls, 0)
  );
  new.escalation_rate_basis_points := case
    when coalesce(new.jobs_count, 0) > 0 then
      round(
        new.escalation_calls::numeric * 10000 / new.jobs_count
      )::integer
    else 0
  end;
  return new;
end;
$function$;

drop trigger if exists camera_usage_daily_sync_escalation_metrics
  on public.camera_usage_daily;
create trigger camera_usage_daily_sync_escalation_metrics
before insert or update on public.camera_usage_daily
for each row execute function private.sync_monitoria_daily_escalation_metrics();

revoke all on function private.sync_monitoria_daily_escalation_metrics()
  from public, anon, authenticated;

-- Recalcula o mês atual com os papéis corrigidos e reabre/resolve alertas reais.
do $block$
begin
  perform set_config('request.jwt.claim.role', 'service_role', true);
  perform public.refresh_monitoria_ai_usage_rollups(
    date_trunc('month', current_date)::date,
    current_date
  );
  perform public.refresh_monitoria_ai_cost_alerts(
    date_trunc('month', current_date)::date
  );
end;
$block$;

commit;
